server:
  port: 0
spring:
  application:
    name: service-consumer-1
eureka:
  client:
    serviceUrl:
      defaultZone: http://bingo:123456@spring-cloud.bingo.com/eureka
#      defaultZone: http://bingo:123456@localhost:9090/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"