package generate.dao;

import generate.model.Subject;

public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Sun Jun 02 22:59:38 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Sun Jun 02 22:59:38 CST 2019
     */
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Sun Jun 02 22:59:38 CST 2019
     */
    int insertSelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Sun Jun 02 22:59:38 CST 2019
     */
    Subject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Sun Jun 02 22:59:38 CST 2019
     */
    int updateByPrimaryKeySelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Sun Jun 02 22:59:38 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Sun Jun 02 22:59:38 CST 2019
     */
    int updateByPrimaryKey(Subject record);
}